version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sa
      - POSTGRES_USER=sa
      - POSTGRES_DB=sponsors
    volumes:
      - sponsors-db:/var/lib/postgresql/data

volumes:
  sponsors-db:
    driver: local