version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: opora
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    networks:
      - ntw
    ports:
      - "9000:8080"
    command:
      - 'start-dev --import-realm'
    restart: always
    depends_on:
      - postgres-keycloak


  postgres-keycloak:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - ntw
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

networks:
  ntw: